### PR TITLE
Add an ability to provide custom rng

### PR DESCRIPTION
**Pull request by ownadi**
This feature is useful when one needs more predictable shuffles.

### CODE REVIEW

**Comment by madox2** [comment]
Hi, thanks for contribution! But I personally find this functionality too specific and I am not sure whether it should be part of the tag cloud. Wouldn't be easier to disable shuffle and pass already shuffled tags (whatever algorithm) into tag cloud?

**Comment by ownadi** [comment]
Personally, I find this feature very convenient and useful. In the way you described, do we need shuffle feature at all? One could always randomize the data outside of the cloud.
I've switched from a similar package (`react-tag-cloud`), which allows overriding rng, and I miss this possibility here. It's obviously totally optional, so most users totally don't need to care about.
Thank you for your work on this library!

**Comment by madox2** [comment]
Alright if you think that it might be beneficial also for other users, I have nothing against it. I would only rename the property to something more meaningful at the first sight, e.g. `randomNumberGenerator`

**Comment by ownadi** [comment]
Sure, it will be better name.

**Pull request merged**
